-- MySQL Script generated by MySQL Workbench
-- Sun Jan 21 18:12:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecms` DEFAULT CHARACTER SET utf8 ;
USE `ecms` ;

-- -----------------------------------------------------
-- Table `ecms`.`donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecms`.`donations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NULL,
  `anonymous_id` INT NULL,
  `amount` DECIMAL NULL,
  `date` DATE NULL,
  `payment_method` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecms`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecms`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecms`.`staff_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecms`.`staff_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NULL,
  `departments_id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  `staff_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `departments_id`),
  INDEX `fk_staff_details_departments1_idx` (`departments_id` ASC),
  CONSTRAINT `fk_staff_details_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `ecms`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecms`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecms`.`members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donations_id` INT NOT NULL,
  `staff_details_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `gender` ENUM('Male', 'Female') NULL,
  `occupation` VARCHAR(45) NULL,
  `phone_num` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `address` VARCHAR(45) NULL,
  `membership_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `donations_id`, `staff_details_id`),
  INDEX `fk_members_donations_idx` (`donations_id` ASC),
  INDEX `fk_members_staff_details1_idx` (`staff_details_id` ASC),
  CONSTRAINT `fk_members_donations`
    FOREIGN KEY (`donations_id`)
    REFERENCES `ecms`.`donations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_staff_details1`
    FOREIGN KEY (`staff_details_id`)
    REFERENCES `ecms`.`staff_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecms`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecms`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `location` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
